[package]
name = "sounding-analysis"
version = "0.10.0"
authors = ["Ryan Leach <clumsycodemonkey@gmail.com>"]
description = """Analysis capability for the sounding-base crate."""
repository = "https://github.com/rnleach/sounding-analysis.git"
readme = "README.md"
license-file = "LICENSE"
exclude = ["**/*.rs.bk",".gitignore",".vscode/**/*","*.sublime*"]
categories = ["science"]
keywords = ["weather","sounding","meteorology", "skew-t"]
edition = "2018"

[dependencies]
itertools = "^0.8.0"
metfor = "^0.7.0"
optional = "^0.5.0"
smallvec = "^0.6"
sounding-base = "^0.10.0"

[dev-dependencies]
sounding-validate = "^0.10.0"

[patch.crates-io]
"metfor" = { path = '../metfor' }
"sounding-base" = { path = '../sounding-base'}
"sounding-validate" = { path = '../sounding-validate'}
