[package]
name = "sounding-analysis"
version = "0.6.0"
authors = ["Ryan Leach <clumsycodemonkey@gmail.com>"]
description = """Analysis capability for the sounding-base crate."""
repository = "https://github.com/rnleach/sounding-analysis.git"
readme = "README.md"
license-file = "LICENSE"
exclude = ["**/*.rs.bk",".gitignore",".vscode/**/*"]
categories = ["science"]
keywords = ["weather","sounding","meteorology", "skew-t"]

[dependencies]
failure = "^0.1.1"
failure_derive = "^0.1.1"
itertools = "^0.7.8"
metfor = "^0.2.4"
smallvec = "^0.6"
sounding-base = "^0.6"

[dev-dependencies]
sounding-validate = "^0.6"
